spring:
  datasource:
    url: jdbc:h2:mem:comicsdb
    username: comics
    password: 123
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    url: jdbc:h2:mem:comicsdb
    user: comics
    password: 123
    baseline-on-migrate: true
