version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: ./mvnw test

  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: ./mvnw package -Dmaven.test.skip=true

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
